version: '3'
services:
  app:
    container_name: nodeEnvironment
    restart: always
    image: node:latest
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - '80:8000'
    depends_on:
      - mongo
    command: "npm run dev"
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
