version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '80:8080'
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
